## Data Encoding 

ML models work with numbers, but real-world datasets often contain categories/text. Encoding converts those categories into numbers in a meaningful way.

1. Nominal/OHE Encoding : Used when categories have no natural order.
2. Label and Ordinal Encoding : Used when categories do have an order.
3. Target Guided Ordinal Encoding : This is a little more advanced.
Instead of assigning numbers arbitrarily, we look at the target variable and determine which category is associated with a higher/lower target value.

## Nominal/OHE Encoding

One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms.

In this technique, each category is represented as a binary vector where each bit corresponds to a unique category.

For example, if we have a categorical variable **"color"** with three possible values (**red, green, blue**), we can represent one hot encoding as follows:

1. Red: `[1, 0, 0]`
2. Green: `[0, 1, 0]`
3. Blue: `[0, 0, 1]`

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
# Create a simple dataframe
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [5]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [6]:
##Create an instance of Onehotencoder
encoder = OneHotEncoder()

In [16]:
## perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [17]:
import pandas as pd
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [18]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [14]:
#for new data
encoder.transform([['blue']]).toarray()

c:\Users\chauh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [19]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0