# Target Guided Ordinal Encoding

It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the **mean or median of the target variable for that category**. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

Target Guided Ordinal Encoding is used when you have a categorical feature and you want to encode its categories based on how strongly they relate to the target variable.

**One-Hot Encoding:** "Give every category its own column."

**Label Encoding:** "Give every category a number."

**Ordinal Encoding:** "Give ordered categories numbers according to their ranking."

**Target Guided Ordinal Encoding:** "Give each category a number based on its relationship with the target."

In [3]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [5]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [6]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [7]:
df['city_encoded'] = df['city'].map(mean_price)

In [8]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [9]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0